// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'footer_inner': string;
  'icon': string;
  'icons': string;
  'link': string;
  'logo': string;
  'text': string;
  'text_wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
