// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'candlestick_chart': string;
  'chart': string;
  'chart_container': string;
  'chart_heading': string;
  'chart_title': string;
  'data_info': string;
  'dot': string;
  'drop_menu': string;
  'time_picker_bottom': string;
  'time_picker_top': string;
  'time_range_picker': string;
  'tooltip': string;
  'trigger': string;
  'trigger_wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
