// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn_lack': string;
  'btn_wait': string;
}
export const cssExports: CssExports;
export default cssExports;
