// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'hidden_mobile': string;
  'user_info': string;
}
export const cssExports: CssExports;
export default cssExports;
