// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add_content': string;
  'arrow': string;
  'balance': string;
  'box': string;
  'btn': string;
  'coin': string;
  'container': string;
  'detail_close': string;
  'detail_item': string;
  'detail_title': string;
  'head': string;
  'icon': string;
  'info_item': string;
  'info_label': string;
  'info_title': string;
  'info_title_swap': string;
  'info_value': string;
  'input': string;
  'item_label': string;
  'item_value': string;
  'key_value': string;
  'line': string;
  'menu': string;
  'menu_item': string;
  'menu_item_selected': string;
  'my_pair_info': string;
  'name': string;
  'normal': string;
  'result_data1': string;
  'result_data2': string;
  'selectToken_wrap': string;
  'switch_icon': string;
  'title': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
