// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'desc': string;
  'disabled': string;
  'info': string;
  'item': string;
  'item_selected': string;
  'left_content': string;
  'line': string;
  'list': string;
  'name': string;
  'options': string;
  'purple': string;
  'rate': string;
  'red': string;
  'right_content': string;
  'status': string;
  'title': string;
  'token_pair': string;
  'unselected': string;
}
export const cssExports: CssExports;
export default cssExports;
