/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    OrderItem: typeof import('./src/components/OrderItem.vue')['default']
    OrderList: typeof import('./src/components/OrderList.vue')['default']
    OrderPanel: typeof import('./src/components/OrderPanel.vue')['default']
    OrderPanelHeader: typeof import('./src/components/OrderPanelHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
