/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AssetsDisplay: typeof import('./src/components/header/AssetsDisplay.vue')['default']
    Claiming: typeof import('./src/components/overlays/Claiming.vue')['default']
    ClaimingOverlay: typeof import('./src/components/overlays/ClaimingOverlay.vue')['default']
    ConfirmationModal: typeof import('./src/components/orders/ConfirmationModal.vue')['default']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    Item: typeof import('./src/components/orders/Item.vue')['default']
    List: typeof import('./src/components/orders/List.vue')['default']
    NavbarMenu: typeof import('./src/components/header/NavbarMenu.vue')['default']
    NotAvailable: typeof import('./src/components/overlays/NotAvailable.vue')['default']
    NotAvailableCover: typeof import('./src/components/NotAvailableCover.vue')['default']
    NotAvailableOverlay: typeof import('./src/components/overlays/NotAvailableOverlay.vue')['default']
    OperationPanel: typeof import('./src/components/pool/OperationPanel.vue')['default']
    OrderConfirmationModal: typeof import('./src/components/orders/OrderConfirmationModal.vue')['default']
    OrderItem: typeof import('./src/components/orders/OrderItem.vue')['default']
    OrderList: typeof import('./src/components/orders/OrderList.vue')['default']
    OrderPanel: typeof import('./src/components/orders/OrderPanel.vue')['default']
    OrderPanelHeader: typeof import('./src/components/orders/OrderPanelHeader.vue')['default']
    PairSelect: typeof import('./src/components/orders/PairSelect.vue')['default']
    PairSelector: typeof import('./src/components/pool/PairSelector.vue')['default']
    Panel: typeof import('./src/components/orders/Panel.vue')['default']
    PanelAdd: typeof import('./src/components/pool/PanelAdd.vue')['default']
    PanelClaim: typeof import('./src/components/pool/PanelClaim.vue')['default']
    PanelHeader: typeof import('./src/components/orders/PanelHeader.vue')['default']
    PanelRemove: typeof import('./src/components/pool/PanelRemove.vue')['default']
    PoolPairSelect: typeof import('./src/components/pool/PoolPairSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/header/TheHeader.vue')['default']
    TheNavbar: typeof import('./src/components/header/TheNavbar.vue')['default']
    UnisatModal: typeof import('./src/components/header/UnisatModal.vue')['default']
  }
}
