// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'amount': string;
  'box': string;
  'btn': string;
  'coin': string;
  'coin_name': string;
  'icon': string;
  'item': string;
  'label': string;
  'left': string;
  'left_content': string;
  'line': string;
  'line1': string;
  'mod': string;
  'mod_content': string;
  'result': string;
  'result_amount': string;
  'result_title': string;
  'right_content': string;
  'symbol': string;
  'time': string;
  'time_title': string;
  'title': string;
  'txid': string;
  'txt': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
