// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'address': string;
  'back': string;
  'balance': string;
  'blue': string;
  'btn': string;
  'container': string;
  'content': string;
  'deposit': string;
  'page_title': string;
  'qrcode': string;
  'tips': string;
  'withdraw': string;
}
export const cssExports: CssExports;
export default cssExports;
