// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'full_name': string;
  'input': string;
  'input_result': string;
  'input_wrap': string;
  'symbol': string;
  'tips': string;
  'title': string;
  'token_info': string;
  'token_name': string;
}
export const cssExports: CssExports;
export default cssExports;
