// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'box': string;
  'coin': string;
  'input': string;
  'input_error': string;
  'name': string;
}
export const cssExports: CssExports;
export default cssExports;
