// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'coin': string;
  'icon': string;
  'info_item': string;
  'info_label': string;
  'info_value': string;
  'item': string;
  'title': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
