// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'coin': string;
  'container': string;
  'create_content': string;
  'done_btn': string;
  'edit': string;
  'finish_desc': string;
  'finish_logo': string;
  'finish_title': string;
  'info': string;
  'label': string;
  'line': string;
  'name': string;
  'no': string;
  'optionButton': string;
  'options': string;
  'selected': string;
  'steps': string;
  'sub_title': string;
  'switch_icon': string;
}
export const cssExports: CssExports;
export default cssExports;
