// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'balance': string;
  'balance_title': string;
  'balance_wrap': string;
  'd': string;
  'data': string;
  'datas': string;
  'input': string;
  'name': string;
  'pair_box': string;
  'pair_left': string;
  'pair_right': string;
  'rate_active': string;
}
export const cssExports: CssExports;
export default cssExports;
