// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app_hide': string;
  'app_title': string;
  'blue': string;
  'box': string;
  'btn': string;
  'container': string;
  'container_center': string;
  'content': string;
  'desc': string;
  'input': string;
  'left': string;
  'left_inner': string;
  'link': string;
  'main_title': string;
  'name': string;
  'pair_box': string;
  'pair_left': string;
  'pair_right': string;
  'right': string;
  'sidebar': string;
  'strong': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
