// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'big': string;
  'btn': string;
  'btn_link': string;
  'dec_desc': string;
  'dec_title': string;
  'decla': string;
  'genesis_id': string;
  'icon_name': string;
  'item': string;
  'menu': string;
  'menu_item': string;
  'menu_item_selected': string;
  'name': string;
  'not': string;
  'search_input': string;
  'selected': string;
  'small': string;
  'token_list': string;
}
export const cssExports: CssExports;
export default cssExports;
