// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'acc_list': string;
  'acc_list_box': string;
  'account': string;
  'account_icon': string;
  'account_trigger': string;
  'address': string;
  'address_qrcode': string;
  'app_title': string;
  'back': string;
  'balance': string;
  'btn': string;
  'btns': string;
  'cancel': string;
  'chooseLogin_dialog': string;
  'connect': string;
  'connect_app': string;
  'dia_title': string;
  'dialog': string;
  'dot': string;
  'ft': string;
  'hd': string;
  'hd_title': string;
  'label': string;
  'line': string;
  'login_dialog': string;
  'persission_title': string;
  'popover': string;
  'qr_code': string;
  'qr_code_content': string;
  'qr_code_title': string;
  'sens_icon': string;
  'sub': string;
  'tips': string;
  'title': string;
  'ts_icon': string;
  'user_pop': string;
  'user_pop_content': string;
  'website': string;
}
export const cssExports: CssExports;
export default cssExports;
