// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abs_item': string;
  'abstract': string;
  'btn_doc': string;
  'btn_doc_arrow': string;
  'btn_start': string;
  'btn_start_arrow': string;
  'btns': string;
  'col_1': string;
  'container': string;
  'content': string;
  'cta': string;
  'feature': string;
  'feature_content': string;
  'feature_icon': string;
  'feature_title': string;
  'features': string;
  'gradient': string;
  'green': string;
  'head': string;
  'head_inner': string;
  'head_right': string;
  'hidden_mobile': string;
  'icon_title': string;
  'label': string;
  'list': string;
  'list_container': string;
  'list_hd': string;
  'list_item': string;
  'logo': string;
  'main': string;
  'main_desc': string;
  'main_intro': string;
  'main_left': string;
  'main_line': string;
  'main_title': string;
  'red': string;
  'title': string;
  'title_h5': string;
  'title_web': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
