// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo': string;
  'menu': string;
  'menu_item': string;
  'menu_item_selected': string;
  'nav_container': string;
  'submenu': string;
  'submenu_item': string;
  'submenu_item_selected': string;
}
export const cssExports: CssExports;
export default cssExports;
