// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'label': string;
  'percent': string;
  'value': string;
  'value2': string;
  'value_wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
