// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app_start_btn_wrap': string;
  'app_title': string;
  'arrow_icon': string;
  'big_btn': string;
  'blank': string;
  'bottom_line': string;
  'close': string;
  'found_desc': string;
  'i_icon': string;
  'icon': string;
  'line': string;
  'plus_icon': string;
  'small_btn': string;
  'switch_icon': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
